server:
  port: 8084
spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: arithmetic
          uri: lb://arithmetic
          predicates:
            - Path=/arithmetic/**
        - id: arithmeticgamification
          uri: lb://arithmeticgamification
          predicates:
            - Path=/gamification/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
      